require('babel-runtime/regenerator')
require('react-hot-loader/patch')
require('babel-register')
require('webpack-hot-middleware/client?reload=true')
require('./assets/styles/main.css')
require('./index.html')
require('./render')